import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "warn",
    // nursery: "warn",
    pedantic: "warn",
    perf: "warn",
    // restriction: "warn",
    // style: "warn",
    suspicious: "warn",
  },
  ignorePatterns: ["convex/_generated"],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "warn",
    typeAware: true,
  },
  overrides: [
    {
      files: ["**/*.test.{ts,tsx}", "**/*.convex.test.{ts,tsx}"],
      rules: {
        "eslint/no-loop-func": "off",
        "jsdoc/check-tag-names": "off",
        "typescript/unbound-method": "off",
        "unicorn/consistent-function-scoping": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "node",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  rules: {
    "eslint/max-depth": "off",
    "eslint/max-lines": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/require-await": "off",
    "eslint/no-inline-comments": "off",
    "eslint/no-negated-condition": "off",
    "eslint/no-warning-comments": "off",
    "import/max-dependencies": "off",
    "import/no-unassigned-import": "off",
    "jest/no-conditional-expect": "off",
    "jest/require-to-throw-message": "off",
    "jsdoc/require-param": "off",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns": "off",
    "jsdoc/require-returns-type": "off",
    "react/jsx-no-constructed-context-values": "off",
    "react/react-in-jsx-scope": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/prefer-top-level-await": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/strict-boolean-expressions": "off",
  },
  settings: {
    react: {
      version: "19",
    },
  },
});
