import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "warn",
    nursery: "warn",
    pedantic: "warn",
    perf: "warn",
    style: "warn",
    suspicious: "warn",
  },
  ignorePatterns: ["convex/_generated"],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "warn",
    typeAware: true,
  },
  overrides: [
    {
      files: ["**/*.test.{ts,tsx}", "**/*.browser.test.{ts,tsx}", "**/*.convex.test.{ts,tsx}"],
      rules: {
        "eslint/no-loop-func": "off",
        "typescript/consistent-return": "off",
        "typescript/strict-void-return": "off",
        "jest/require-hook": "off",
        "jsdoc/check-tag-names": "off",
        "typescript/unbound-method": "off",
        "unicorn/consistent-function-scoping": "off",
      },
    },
    {
      files: ["scripts/**"],
      rules: {
        "eslint/no-console": "off",
      },
    },
    {
      files: [
        "app/routes/**",
        "app/root.tsx",
        "app/entry.*.tsx",
        "app/providers/**",
        "app/components/ui/**",
      ],
      rules: {
        "react/only-export-components": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "node",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  rules: {
    "eslint/arrow-body-style": "off",
    "eslint/capitalized-comments": "off",
    "eslint/curly": "off",
    "eslint/id-length": "off",
    "eslint/init-declarations": "off",
    "eslint/max-depth": "off",
    "eslint/max-lines": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/max-params": "off",
    "eslint/max-statements": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/no-undef": "off",
    "eslint/no-continue": "off",
    "eslint/no-inline-comments": "off",
    "eslint/no-magic-numbers": "off",
    "eslint/no-negated-condition": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-ternary": "off",
    "eslint/no-warning-comments": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/prefer-readonly-parameter-types": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "eslint/require-await": "off",
    "eslint/sort-imports": "off",
    "eslint/sort-keys": "off",
    "import/consistent-type-specifier-style": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/no-unassigned-import": "off",
    "import/prefer-default-export": "off",
    "jest/no-conditional-expect": "off",
    "jest/require-hook": "off",
    "jest/require-to-throw-message": "off",
    "jsdoc/require-param": "off",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns": "off",
    "jsdoc/require-returns-type": "off",
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "react/jsx-handler-names": "off",
    "react/jsx-max-depth": "off",
    "react/jsx-no-constructed-context-values": "off",
    "react/jsx-props-no-spreading": "off",
    "react/no-set-state": "off",
    "react/react-in-jsx-scope": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-null": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/prefer-global-this": "off",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-top-level-await": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/prefer-called-once": "off",
    "vitest/prefer-called-times": "off",
    "vitest/prefer-import-in-mock": "off",
    // --- cherry-picked from restriction ---
    "eslint/no-console": ["warn", { allow: ["error", "info", "warn"] }],
    "eslint/no-explicit-any": "warn",
    "jsx-a11y/anchor-ambiguous-text": "warn",
    "react/only-export-components": "warn",
    "unicorn/no-array-for-each": "warn",
    "unicorn/prefer-number-properties": "warn",
  },
  settings: {
    react: {
      version: "19",
    },
  },
});
