import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "warn",
    nursery: "warn",
    pedantic: "warn",
    perf: "warn",
    style: "warn",
    suspicious: "warn",
  },
  ignorePatterns: ["convex/_generated"],
  jsPlugins: ["eslint-plugin-perfectionist"],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "warn",
    typeAware: true,
  },
  overrides: [
    {
      files: ["**/*.test.{ts,tsx}", "**/*.browser.test.{ts,tsx}", "**/*.convex.test.{ts,tsx}"],
      rules: {
        "eslint/no-loop-func": "off",
        // We use vitest, not jest. oxlint bundles both rulesets and many rules
        // fire from both plugins simultaneously — including some with autofixes
        // that don't see each other's edits (see prefer-expect-assertions).
        // Disable every jest/* rule that has a vitest counterpart, plus
        // jest-only rules that don't apply to vitest.
        "jest/max-expects": "off",
        "jest/no-conditional-in-test": "off",
        "jest/no-done-callback": "off", // vitest has no done callback
        "jest/no-hooks": "off",
        "jest/no-untyped-mock-factory": "off",
        "jest/prefer-called-with": "off",
        "jest/prefer-ending-with-an-expect": "off",
        "jest/prefer-expect-assertions": "off",
        "jest/prefer-hooks-in-order": "off",
        "jest/prefer-spy-on": "off",
        "jest/prefer-strict-equal": "off",
        "jest/require-hook": "off",
        "jest/require-top-level-describe": "off",
        "jsdoc/check-tag-names": "off",
        "typescript/consistent-return": "off",
        "typescript/no-unsafe-return": "off",
        "typescript/strict-void-return": "off",
        "typescript/unbound-method": "off",
        "unicorn/consistent-function-scoping": "off",
        "vitest/max-expects": "off",
        "vitest/no-conditional-expect": "off",
        "vitest/no-conditional-in-test": "off",
        // Project convention (see .claude/rules/testing.md): simple test() calls,
        // not describe/it. So disable describe/hooks-shaped rules.
        "vitest/no-hooks": "off",
        // Conflicts with vitest's `({ expect }) => ...` fixture pattern — the
        // rule misreads it as shadowing.
        "vitest/prefer-expect-assertions": "off",
        "vitest/require-mock-type-parameters": "off",
        "vitest/require-top-level-describe": "off",
      },
    },
    {
      files: ["scripts/**"],
      rules: {
        "eslint/no-console": "off",
      },
    },
    {
      files: [
        "app/routes/**",
        "app/root.tsx",
        "app/entry.*.tsx",
        "app/providers/**",
        "app/components/ui/**",
      ],
      rules: {
        "react/only-export-components": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "node",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  rules: {
    "eslint/arrow-body-style": "off",
    "eslint/capitalized-comments": "off",
    "eslint/curly": "off",
    "eslint/id-length": "off",
    "eslint/init-declarations": "off",
    "eslint/max-depth": "off",
    "eslint/max-lines": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/max-params": "off",
    "eslint/max-statements": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/no-console": ["warn", { allow: ["error", "info", "warn"] }],
    "eslint/no-continue": "off",
    "eslint/no-inline-comments": "off",
    "eslint/no-magic-numbers": "off",
    "eslint/no-negated-condition": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-ternary": "off",
    "eslint/no-undef": "off",
    "eslint/no-underscore-dangle": [
      "warn",
      { allow: ["_id", "_creationTime", "_storageId", "__serialized__"] },
    ],
    "eslint/no-warning-comments": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/require-await": "off",
    "eslint/sort-imports": "off",
    "eslint/sort-keys": "off",
    "import/consistent-type-specifier-style": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/no-unassigned-import": "off",
    "import/prefer-default-export": "off",
    "jest/no-conditional-expect": "off",
    "jest/require-hook": "off",
    "jest/require-to-throw-message": "off",
    "jsdoc/require-param": "off",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns": "off",
    "jsdoc/require-returns-type": "off",
    "jsx-a11y/anchor-ambiguous-text": "warn",
    "perfectionist/sort-array-includes": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-decorators": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-enums": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-export-attributes": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-exports": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-heritage-clauses": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-import-attributes": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-interfaces": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-intersection-types": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-jsx-props": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-maps": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-named-exports": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-object-types": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-objects": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-sets": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-switch-case": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-union-types": ["warn", { order: "asc", type: "natural" }],
    "perfectionist/sort-variable-declarations": ["warn", { order: "asc", type: "natural" }],
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "react/jsx-handler-names": "off",
    "react/jsx-max-depth": "off",
    "react/jsx-no-constructed-context-values": "off",
    "react/jsx-props-no-spreading": "off",
    "react/no-set-state": "off",
    "react/only-export-components": "warn",
    "react/react-in-jsx-scope": "off",
    "typescript/no-explicit-any": "warn",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-array-for-each": "warn",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-null": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/prefer-global-this": "off",
    "unicorn/prefer-number-properties": "warn",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-top-level-await": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/prefer-called-once": "off",
    "vitest/prefer-called-times": "off",
    "vitest/prefer-import-in-mock": "off",
    "vitest/prefer-strict-boolean-matchers": "off",
  },
  settings: {
    react: {
      version: "19",
    },
  },
});
