export const CREDIT_CARD_PRESETS = [
  {
    cardType: "cashback" as const,
    id: "costco-visa",
    isCustomizable: true,
    isPreset: true,
    issuer: "Citi",
    name: "Costco Anywhere Visa",
    pointsPerDollar: 2,
    valuePerPoint: 0.01,
  },
  {
    cardType: "travel" as const,
    id: "freedom-unlimited",
    isCustomizable: true,
    isPreset: true,
    issuer: "Chase",
    name: "Freedom Unlimited",
    pointsPerDollar: 1.5,
    valuePerPoint: 0.021,
  },
  {
    cardType: "travel" as const,
    id: "venture-x",
    isCustomizable: true,
    isPreset: true,
    issuer: "Capital One",
    name: "Capital One Venture X",
    pointsPerDollar: 2,
    valuePerPoint: 0.0185,
  },
  {
    cardType: "travel" as const,
    id: "strata-premier",
    isCustomizable: true,
    isPreset: true,
    issuer: "Citi",
    name: "Strata Premier",
    pointsPerDollar: 1,
    valuePerPoint: 0.019,
  },
  {
    cardType: "cashback" as const,
    id: "robinhood",
    isCustomizable: true,
    isPreset: true,
    issuer: "Robinhood",
    name: "Robinhood Gold Card",
    pointsPerDollar: 3,
    valuePerPoint: 0.01,
  },
] as const;
